### ISSUE TITLE
Rename hatchGripper.java to HatchGripper.java

### ISSUE THREAD

**Issue by rudabegga** [Monsters-308/FRC2019_308#1]
Class declarations need to match the filename.  in Java / any other Object oriented language the Class names are typed in PascaleCase notation. While Internal Members are typed in camelCase notation.

This helps programmers know if it is a class declaration, or an internal member / member function.

So for compailation you need to change hatchGripper.java to HatchGripper.java.

**Comment by MatteoMoceri** [comment]
HatchGripper was renamed in the code, but the title on GitHub is still lowercase
